# Library properties
BUILDNAME=PVTP
CC= g++
LIBNAME=lib$(BUILDNAME)
RAPIDXML=rapidxml
RAPIDXMLVER=1.13
LIBVER=0.1.0

# Path for shared library/header installation
LIB_PATH=/usr/local

# Library bookkeeping... probably won't need to edit any of this
UNAME=$(shell uname)
ifeq ($(UNAME), Darwin)
	LIBEXT=dylib
else
	LIBEXT=so
endif
LIBFULLNAME=$(LIBNAME)-$(LIBVER).$(LIBEXT)
LIBLINKNAME=$(LIBNAME).$(LIBEXT)
LIBRARY=$(LIBFULLNAME)
LIB_INSTALL_PATH=$(LIB_PATH)/lib
LIB_INCLUDE_PATH=$(LIB_PATH)/include

# Local path information, don't change
SRCDIR = src
LOCALINC = include

# GSL info
BUILD_GSL=0
GSLINC=/opt/local/include
GSLLIB=/opt/local/lib

# BOOST info
BUILD_BOOST=1
BOOSTINC=/opt/local/include

# Build properties: shared = 1, or static = 0
BUILD_TYPE=0

# Whether to build JNI support; set the include paths below.
# This requires you have Java on your system, and that the PVTP library is built as a shared library
BUILD_JNI=1

# Platform-dependent Java libraries; only needed if you're building JNI support
MAC_JAVA_INC_DIR= /System/Library/Frameworks/JavaVM.framework/Headers
LINUX_JAVA_INC_DIR= /usr/lib/jvm/java-1.7.0-openjdk-amd64/include
